spring:
  cloud:
    stream:
      bindings:
        input:
          destination: subscriber
          group: group
          binder: rabbit
          consumer:
            concurrency: 8
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost